language: java

jdk:
  - openjdk8

env:
  global:
    # BINTRAY_USER
    - secure: "QNq1jufsXivxf7jNDb98zJ2sVw6K29uf0hBU87rNhjqaA7d81xmIYDZ36cl6WQHB2o4xoMkVYaLJi2h/6xLiUPCwubCQmneQZQikngRWicMT3sfCADLsxAcIhzAN+a2/UWq5I6gBpjS5jKHFLsQ0cD8g/87rwcuo647QMy8S43mzsqYKbQhEzk7WjUG0vI27J7kriuLGMppLWuqIL6IOlmjrdmJlPMrHqk+fDEpPKj3q++3talGrWmzPdd7WYcUnfwEzqUd3aeEA//KRheznnrSyjy7MCtLqsQrxa9vouZ0viYu6bCXWz7NmbXHfmrrQ0dOgSgREukx5hahIW8l2JW7TZYlMfsFaPIiw6bhPrgbmADEt/f+KRLADX+lqRfH4A/TqnlNwK/HGQe9NIcyVrvHzga4n6XyZL0exUODkqHT3suJ52jTimA/2bMeI+fl1UFQBS+Gfz8TcuE3YVF7i/jSHU8+1Lg/3ju1W2Lsrz7z+N2peZyKYIIxpBbW+ksN6FrgE5P1tHMqLraV8ZXYIZAOQPksa6uwYkChU77jtIhGMUN7A1Xawq3OuBqm4BEWFTqbzE0d6G9o/Uwk/1qcMii3ZlcVLV9Gfd2b2c8/+53HglJ/PN4xUmKLxlgHYIHE/LmhVpQp0ZZi4ZSeL7/euS81eQ6Xg4cwXD/PCjOGIDd0="
    # BINTRAY_KEY
    - secure: "wagTTF6AXFGxQm14dl7uHSd6gD/Zd2Aqs5IyZLr75Vvku8jnGrcRMNHdHi3y2Ayzo3lmN2o0LvEnJH94euGIWD8P3k6ttBimbPQLMsrsKYKYrfyeSJKZK8bB/RL0TJsLDzoK5RFLXowmcS6emuw31YPZGHAem4Rr9P5/2dDChapql8xodH0A3KgEK/fdvExVPfjko46cx1phdX/vts01Q3tWDkihZvntrKdZsS2ZyuhV/OherPnQTRaDKrw8+YgHo7eJVWKdhNR081pYRrSLqwzaf+ComdAdbfVDTqGHS658KnAFG5AeFdQexjyspv5Tz4mB/+Cp7I1tp7rxNK3aO7TZrsdBlmefrUlIjplz6tRiM8CoppXeKleXamzTOxDaVA5s6KVv9FjY7mY3goeiO8ZkIGIc+nXimyBbkMPVvLshaoeuFjJdaNBFw660hTbkU7/xTBVzHKhpLa3VWizbyw5V4AF1KxfdF+jxIzuFI9bfCtsaU9utWGEf30O+nvbwfw20mEQ0xusnDJn4ei+TWKKKRKf+5JhMU9mRsfzyYgxoAo1B2ChtgyIr+aaOblPVnetbLJCR/TqLs94aDczmlhIfeL4X0x1Li9sQcVzeS+4YI6GC3O+hyA+1WaUSu+yVntwIP8bGp4jd8OscWhr4biSFJAzBpAXtgnVCjbBHHEU="

install: ./gradlew clean
before_script:
  - ./go.sh docker
script: ./gradlew test

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    on:
      tags: true

cache:
  directories:
    - ~/.gradle/
